
substitutions:
# Unique name for this configuration, only use Latin letters and numbers, no spaces or
# special characters, e.g., "tclac". If there will be several air conditioner modules, the device_name must be changed,
# for example, by adding numbers: tclac1, tclac2, tclac3...
  device_name: tclac
# Human-friendly name for the air conditioner, for the interface:
  friendly_name: TCL Air Conditioner
# WiFi connection settings, data can be stored in the "secret" file in ESPHome, if not- edit here:
# WiFi Access Point name:
  wifi_ssid: !secret wifi_ssid
# WiFi Access Point password:
  wifi_password: !secret wifi_password
# Password for the recovery access point, the access point name will be: "{device_name} Fallback Hotspot"
  recovery_pass: mKSzmBdt7DAj
# Password for over-the-air updates, generated once and then always used automatically:
  ota_pass: 90cf525a594c8bb2cbf917bc2c2fa058
# Connection key for the Home Assistant API, a new key can be obtained here: https://esphome.io/components/api.html:
  api_key: lmUoWsWs1oqSfJqLFsA6PisHSx4Y1G+iu7V3PDIqpXk=
# Module pins to which UART is connected:
  uart_rx: GPIO3
  uart_tx: GPIO1
# Module pins for connecting signaling LEDs, for them to work you need to uncomment "leds" in "packages"
# otherwise it will not work at all and you can write anything here. For those who asked to remove them.
  receive_led: GPIO6
  transmit_led: GPIO4

# Included files- loaded and updated automatically from the internet, uncomment the ones you need
# Option descriptions:
# - packages/leds.yaml - LEDs for transmit/receive indication, pins are specified in receive_led / transmit_led
#
# Aligning uncommented lines to the specified position is mandatory!
packages:
  remote_package:
    url: https://github.com/chindocaine/tclac.git
    ref: master
    files:
    # v - align lines with options at this position, otherwise it will glitch
      - packages/core.yaml # The core of all things
      # - packages/leds.yaml
    refresh: 30s

# Selected module to be flashed with this firmware. You can uncomment a ready-made template, deleting the existing one:

# ESP-01S
esp8266:
  board: esp01_1m

# Hommyn HDN/WFN-02-01, from the first article
#esp32:
#  board: esp32-c3-devkitm-1
#  framework:
#    type: arduino

# Status LED. Enable as desired if free pins are available
#status_led:
#  pin:
#    number: GPIO5
#    inverted: false
