# Climate component
external_components:
  - source:
      url: https://github.com/chindocaine/tclac.git
      type: git
      ref: master
    components: [ tclac ]
    refresh: 30s

# ESPHome configuration
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2025.11.0
  on_boot:
    priority: -100
    then:
      lambda: !lambda |-
        id(air_conditioner).set_beeper_state(false);
        id(air_conditioner).set_force_mode_state(false);

        if (id(display_mode).state){
          id(air_conditioner).set_display_state(true);
        } else {
          id(air_conditioner).set_display_state(false);
        }
        if (id(beep_mode).state){
          id(air_conditioner).set_beeper_state(true);
        } else {
          id(air_conditioner).set_beeper_state(false);
        }
        if (id(force_mode).state){
          id(air_conditioner).set_force_mode_state(true);
        } else {
          id(air_conditioner).set_force_mode_state(false);
        }

uart:
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  stop_bits: 1
  rx_pin: ${uart_rx}
  tx_pin: ${uart_tx}

api:
  encryption:
    key: "${api_key}"

ota:
- platform: esphome
  password: "${ota_pass}"

wifi:
  id: "${device_name}_wifi"
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: "${recovery_pass}"

captive_portal:


# MUST disable logging via UART
logger:
  baud_rate: 0

# Device settings section:
# - Switches
switch:
  # Beeper to confirm commands, disabled by default
  - name: Beeper
    platform: template
    device_class: switch
    id: beep_mode
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    on_turn_on:
      then:
        lambda: !lambda |-
          id(air_conditioner).set_beeper_state(true);
    on_turn_off:
      then:
        lambda: !lambda |-
          id(air_conditioner).set_beeper_state(false);
  
  # Temperature setpoint indicator on the indoor unit body, enabled by default
  - name: Display
    platform: template
    device_class: switch
    id: display_mode
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    on_turn_on:
      then:
        lambda: !lambda |-
          id(air_conditioner).set_display_state(true);
    on_turn_off:
      then:
        lambda: !lambda |-
          id(air_conditioner).set_display_state(false);
  
  - name: Force config
    platform: template
    device_class: switch
    id: force_mode
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    on_turn_on:
      then:
        lambda: !lambda |-
          id(air_conditioner).set_force_mode_state(true);
    on_turn_off:
      then:
        lambda: !lambda |-
          id(air_conditioner).set_force_mode_state(false);

climate:
  - platform: tclac
    name: "Air Conditioner"
    id: air_conditioner